// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function IndexReplays() {
  return window['go']['main']['App']['IndexReplays']();
}

export function LoadReplay(arg1) {
  return window['go']['main']['App']['LoadReplay'](arg1);
}
