// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {bsor} from '../models';

export function GetCwd():Promise<string>;

export function IndexReplays(arg1:number,arg2:number,arg3:boolean):Promise<Array<main.ReplayItem>>;

export function LoadReplay(arg1:string):Promise<bsor.ReplayEventsWithStats>;

export function WatchReplaysDirectory():Promise<void>;
