// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCwd() {
  return window['go']['main']['App']['GetCwd']();
}

export function IndexReplays(arg1, arg2, arg3) {
  return window['go']['main']['App']['IndexReplays'](arg1, arg2, arg3);
}

export function LoadReplay(arg1) {
  return window['go']['main']['App']['LoadReplay'](arg1);
}

export function WatchReplaysDirectory() {
  return window['go']['main']['App']['WatchReplaysDirectory']();
}
